name: Source code only changes
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - '**.php'
      - '!tests/**'
      - '!examples/**'
      - '!config/**'
      - '!.phan/**'
permissions:
  contents: read
  security-events: write
jobs:
  integration_tests:
    uses: ./.github/workflows/integration-tests.yml
  PHPMD:
    uses: phpolar/github-workflows/.github/workflows/phpmd.yml@v1
    secrets: inherit
